export const languageFileName = {
  c: "Solution.c",
  cpp: "Solution.cpp",
  csharp: "Solution.cs",
  dart: "Solution.dart",
  elixir: "solution.ex",
  erlang: "solution.erl",
  go: "solution.go",
  java: "Solution.java",
  javascript: "solution.js",
  kotlin: "Solution.kt",
  php: "Solution.php",
  python: "solution.py",
  ruby: "solution.rb",
  rust: "solution.rs",
  scala: "Solution.scala",
  swift: "Solution.swift",
  typescript: "solution.ts",
};
